config/routes.rb
Spree::Core::Engine.add_routes do
  resources :contacts, :controller => 'contact_us/contacts', :only => [:new, :create]
  get 'contact-us' => 'contact_us/contacts#new', :as => :contact_us
end

app/models/spree/contact_us/contact.rb
module Spree
  module ContactUs
    class Contact

      include ActiveModel::Conversion
      include ActiveModel::Validations

      attr_accessor :email, :message, :name, :subject

      EMAIL_REGEX = /\A
        [^\s@]+ # non-at-sign characters, at least one
          @     # at-sign
        [^\s.@] # non-at-sign and non-period character
        [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
         \.     # period
        [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
        [^\s.@] # non-at-sign and non-period character
      \z/x

      validates :email,   :format => { :with => EMAIL_REGEX },
                          :presence => true
      validates :message, :presence => true
      validates :name,    :presence => {:if => Proc.new{SpreeContactUs.require_name}}
      validates :subject, :presence => {:if => Proc.new{SpreeContactUs.require_subject}}

      def initialize(attributes = {})
        [:email, :message, :name, :subject].each do |attribute|
          self.send("#{attribute}=", attributes[attribute]) if attributes and attributes.has_key?(attribute)
        end
      end

      def save
        if self.valid?
          Spree::ContactUs::ContactMailer.contact_email(self).deliver_now
          return true
        end
        false
      end

      def persisted?
        false
      end
    end
  end
end

app/controllers/spree/contact_us/contacts_controller.rb
class Spree::ContactUs::ContactsController < Spree::StoreController

  helper "spree/products"
  def create
    @contact = Spree::ContactUs::Contact.new(params[:contact_us_contact])

    if @contact.save
      if Spree::ContactUs::Config.contact_tracking_message.present?
        flash[:contact_tracking] = Spree::ContactUs::Config.contact_tracking_message
      end
      redirect_to(spree.root_path, :notice => Spree.t('contact_us.notices.success'))
    else
      render :new
    end
  end

  def new
    @contact = Spree::ContactUs::Contact.new
    @taxonomies = Spree::Taxonomy.includes(root: :children)
  end

  private

    def accurate_title
      Spree.t(:contact_us_title)
    end

end

app/views/spree/contact_us/contacts/new.html.erb
<div class="contact-section">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="titie-section wow fadeInDown animated ">
          <h1>GET IN TOUCH</h1>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 wow fadeInLeft animated">
        <div class="left-content">
          <h1><span>M</span>art</h1>
          <h3>We'd love To Meet You In Person Or Via The Web!</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel nulla sapien. Class aptent tacitiaptent taciti sociosqu ad lit himenaeos. Suspendisse massa urna, luctus ut vestibulum necs et, vulputate quis urna. Donec at commodo erat.</p>
          <div class="contact-info">
            <p><b>Main Office:</b> 123 Elm St. New York City, NY</p>
            <p><b>Phone:</b> 1.555.555.5555</p>
            <p><b>Email:</b> info@yourdomain.com</p>
          </div>
          <div class="social-media">
            <ul>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a href="#"><i class="fa fa-instagram"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-6 wow fadeInRight animated">
        <%= form_for @contact, :url => contacts_path, :html => { :novalidate => '' } do |f| %>
            <div class="row">
              <% if SpreeContactUs.require_name %>
                  <div class="col-md-12">
                    <div class="input-group">
                      <p>
                        <%= f.text_field :name, class: 'required form-control', placeholder: 'Your Name...' %>
                      </p>
                    </div>
                  </div>
              <% end %>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="input-group">
                  <p>
                    <%= f.email_field :email, class: 'required form-control email', placeholder: 'Your Email...' %>
                  </p>
                </div>
              </div>
            </div>
            <div class="row">
              <% if SpreeContactUs.require_subject %>
                  <div class="col-md-12">
                    <div class="input-group">
                      <p>
                        <%= f.text_field :subject, class: 'required form-control', placeholder: 'Your Subject...'  %>
                      </p>
                    </div>
                  </div>
              <% end %>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="input-group">
                  <%= f.text_area :message, class: 'required form-control', placeholder: 'Your Message...' %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="input-group">
                  <%= f.submit Spree.t(:submit), :alt => Spree.t(:submit), :id => 'contact_us_contact_submit', :class => 'contact-submit', :title => Spree.t(:submit) %>
                </div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>